version: '3'
services:

  app:
    image: n8nio/n8n
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "5678:5678"
    volumes:
      - ./n8n:/home/node/.n8n


# docker run -it --rm --name n8n -p 5678:5678 -v n8n_data:/home/node/.n8n 